/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Aowal
 */

#include <bits/stdc++.h>
#include <iostream>

using namespace std;

class TaskB {
public:
    void solve(std::istream &in, std::ostream &out) {
        int h, m, s, t1, t2;
        in >> h >> m >> s >> t1 >> t2;
        double a = (6.0 * s) > 360 ? (6.0 * s) - 360 : (6.0 * s);
        double b = (6.0 * (m + s / 60.0)) > 360 ? (6.0 * (m + s / 60.0)) - 360 : (6.0 * (m + s / 60.0));
        double c = (.5 * (60 * h + (m + s / 60.0))) > 360 ? .5 * (60 * h + (m + s / 60.0)) - 360 : .5 * (60 * h + (m +
                                                                                                                   s /
                                                                                                                   60.0));
        double x = t1 * 30 % 360;
        double y = t2 * 30 % 360;
        if (x > y)
            swap(x, y);
        int count = 0;
        if (a > x && a < y)
            count++;
        if (b > x && b < y)
            count++;
        if (c > x && c < y)
            count++;
        if (count == 0 || count == 3) {
            out << "YES";
        } else {
            out << "NO";
        }

    }
};


int main() {
    TaskB solver;
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    cout.tie(NULL);
    std::istream &in(std::cin);
    std::ostream &out(std::cout);
    solver.solve(in, out);
    return 0;
}
