/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author HSK
 */

//#include <iostream>
//#include <fstream>

#include <bits/stdc++.h>
using namespace std;

class TaskA {
 public:
  void solve(std::istream& in, std::ostream& out) {
    string password;
    in >> password;
    int n;
    in >> n;
    vector<string> K(n);

    bool first = false, second = false;
    for (int i = 0; i < n; i++) {
      in >> K[i];
      if (K[i] == password) {
        first = second = true;
      }
    }

    for (int i = 0; i < n; i++) {
      if (K[i][0] == password[1]) {
        second = true;
      }
      if (K[i][1] == password[0]) {
        first = true;
      }
    }

    if (first && second) {
      out << "YES\n";
    } else {
      out << "NO\n";
    }
  }
};


int main() {
    std::ios_base::sync_with_stdio(false);
    std::cin.tie(NULL);
	TaskA solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
