/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Harshad
 */

#include <iostream>
#include <fstream>

#include <iostream>

class TaskA {
public:
    void solve(std::istream &in, std::ostream &out) {
        std::string s;
        in >> s;
        int n;
        in >> n;
        std::string temp;
        bool c1 = false, c2 = false;
        for (int i = 0; i < n; ++i) {
            in >> temp;
            if (temp == s) {
                out << "YES";
                return;
            }
            if (temp[1] == s[0]) c1 = true;
            if (temp[0] == s[1]) c2 = true;
        }
        if (c1 && c2) out << "YES";
        else out << "NO";

    }
};


int main() {
    TaskA solver;
    std::istream &in(std::cin);
    std::ostream &out(std::cout);
    solver.solve(in, out);
    return 0;
}
