/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Aowal
 */

#include <bits/stdc++.h>
#include <iostream>

using namespace std;

class TaskA {
public:
    void solve(std::istream &in, std::ostream &out) {
        string a, b;
        in >> a;
        int n;
        in >> n;
        bool flag1 = false, flag2 = false;
        for (int j = 0; j < n; ++j) {
            in >> b;
            if (a == b) {
                out << "YES";
                return;
            } else if (b[0] == a[1] && b[1] == a[0]) {
                out << "YES";
                return;
            }
            if (b[0] == a[1]) {
                flag1 = true;
            }
            if (b[1] == a[0]) {
                flag2 = true;
            }
        }
        if (flag1 && flag2) {
            out << "YES";
            return;
        } else {
            out << "NO";
            return;
        }

    }
};


int main() {
    TaskA solver;
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    cout.tie(NULL);
    std::istream &in(std::cin);
    std::ostream &out(std::cout);
    solver.solve(in, out);
    return 0;
}
