/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Harshad
 */

#include <bits/stdc++.h>
#define f(i,n) for(int i=0;i<n;i++)
#define rep(i,a,b) for(int i=a;i<=b;i++)
typedef long long int ll;
using namespace std;

class TaskC {
public:
    ll a[100005], b[100005];
    ll n, s;

    ll cost(ll k){
        f(i, n) b[i] = a[i] + (i+1)*k;
        sort(b, b+n);
        ll res=0;
        f(i, k) res+=b[i];
        return res;
    }
	void solve(std::istream& in, std::ostream& out) {
        in>>n>>s;
        f(i, n) in>>a[i];
        ll l=1, h=n;
        ll ans=0;
        while(l<=h){
            ll mid = (l+h)>>1;
            if(cost(mid)<=s){
                ans = mid;
                l=mid+1;
            }
            else h=mid-1;
        }
        out<<ans<<" "<<cost(ans);


	}
};


int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
	TaskC solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
