/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Harshad
 */

#include <bits/stdc++.h>
#define f(i,n) for(int i=0;i<n;i++)
#define rep(i,a,b) for(int i=a;i<=b;i++)
typedef long long int ll;
using namespace std;

class TaskC {
public:
	void solve(std::istream& in, std::ostream& out) {
        string s; in>>s;
        ll nb, ns, nc; in>>nb>>ns>>nc;
        ll pb, ps, pc; in>>pb>>ps>>pc;
        ll r; in>>r;
        ll rb=0, rs=0, rc=0;
        f(i, s.length()){
            if(s[i]=='B') rb++;
            else if(s[i]=='S') rs++;
            else rc++;
        }
        ll low=0, high=10000000000000;
        ll res=-1;
        while(low<=high){
            ll x = (low+high)>>1;
            ll cost = max(0LL, rb*x-nb)*pb + max(0LL, rs*x-ns)*ps + max(0LL, rc*x-nc)*pc;
            if(cost<=r){
                res = x;
                low = x+1;
            }
            else high = x-1;
        }
        out<<res;

	}
};


int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
	TaskC solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
