/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Harshad
 */

#include <bits/stdc++.h>
#define f(i,n) for(int i=0;i<n;i++)
#define rep(i,a,b) for(int i=a;i<=b;i++)
typedef long long int ll;
using namespace std;

class TaskC {
public:
    int a[100001], b[100001];
	void solve(std::istream& in, std::ostream& out) {
        int n, k; in>>n>>k;
        string s; in>>s; s=" "+s;
        rep(i, 1, n) a[i]=a[i-1]+(s[i]=='a'), b[i]=b[i-1]+(s[i]=='b');
        int res=1;
        rep(i, 1, n){
            int l=i, r=n;
            while(l<r){
                int mid = (l+r+1)>>1;
                if(a[mid]-a[i-1]<=k or b[mid]-b[i-1]<=k) l=mid;
                else r=mid-1;
            }
            res = max(res, l-i+1);
        }
        out<<res;
	}
};


int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
	TaskC solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
