/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author HARSHAD
 */

#include <bits/stdc++.h>
using namespace std;
typedef long long int ll;

class ProblemDMultiplicationTable {
public:
	ll n, m, k;
	ll get(ll val){
		--val;
		ll res = 0;
		for(ll i = 1; i<=n; ++i){
			res += min(val/i, m);
		}
		return res;
	}
	void solve(std::istream& in, std::ostream& out) {
		in>>n>>m>>k;
		ll low = 1, high = n*m;
		ll res = -1;
		while(low<=high){
			ll mid = (low+high)>>1;
			if(get(mid)<=k-1){
				res = mid;
				low = mid + 1;
			}
			else high = mid - 1;
		}
		out<<res;
	}
};


int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
	ProblemDMultiplicationTable solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
