/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author HARSHAD
 */

#include <bits/stdc++.h>
#define f(i,n) for(int i=0;i<n;i++)
#define rep(i,a,b) for(int i=a;i<=b;i++)
using namespace std;
typedef vector<int> vi;
typedef long long int ll;

class TaskB {
public:
	ll rec(ll n, ll k){
		ll size = (1LL<<n)-1;
		if(k==size/2+1) return n;
		if(k<size/2+1) return rec(n-1, k);
		else return rec(n-1, k-(size/2+1));
	}
	void solve(std::istream& in, std::ostream& out) {
		ll n, k; in>>n>>k;
		out<<rec(n, k);
	}
};


int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
	TaskB solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
